// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjEIb5Zamqal33RKWG6uoZMjZDsFd7ho',
    appId: '1:973376203011:web:6a8847e1665e0c9306a136',
    messagingSenderId: '973376203011',
    projectId: 'brainbook-admin',
    authDomain: 'brainbook-admin.firebaseapp.com',
    storageBucket: 'brainbook-admin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Bu6qV7ehNTF2dDEj0kCuKaa6TnrRAFk',
    appId: '1:973376203011:android:91a9980f82ee0f5d06a136',
    messagingSenderId: '973376203011',
    projectId: 'brainbook-admin',
    storageBucket: 'brainbook-admin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKOKFxVglToAZELz9gqLBz-h9H0KYBZ0',
    appId: '1:973376203011:ios:7a1e0013bd96e5e006a136',
    messagingSenderId: '973376203011',
    projectId: 'brainbook-admin',
    storageBucket: 'brainbook-admin.appspot.com',
    iosClientId: '973376203011-ojqe0hej4r1dqfnpeb8r6bnb1mbk3dk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainBookAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuKOKFxVglToAZELz9gqLBz-h9H0KYBZ0',
    appId: '1:973376203011:ios:7a1e0013bd96e5e006a136',
    messagingSenderId: '973376203011',
    projectId: 'brainbook-admin',
    storageBucket: 'brainbook-admin.appspot.com',
    iosClientId: '973376203011-ojqe0hej4r1dqfnpeb8r6bnb1mbk3dk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainBookAdmin',
  );
}
